name: Promo Common Service CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn --file pom.xml clean install

#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-west-2
#
#      - name: Deploy to EC2
#        env:
#          EC2_HOST: ${{ secrets.EC2_HOST }}
#          EC2_USER: ${{ secrets.EC2_USER }}
#          EC2_KEY: ${{ secrets.EC2_KEY }}
#        run: |
#          scp -i $EC2_KEY promo-common/target/promo-common.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/promo-common.jar
#          ssh -i $EC2_KEY $EC2_USER@$EC2_HOST 'sudo systemctl restart promo-common-service'
